# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-DarmstadtPM-TieHash
version:      0.2
version_from: lib/Acme/DarmstadtPM/TieHash.pm
installdirs:  site
requires:
    Tie::ListKeyedHash:            1.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
